#!/bin/bash


# config ----------

gogs_token=""
gogs_token_envvar=GOGS_API_TOKEN
gogs_token_filename=gogs-api-token.txt

gogs_server="" # https://try.gogs.io
gogs_server_envvar=GOGS_SERVER_URL
gogs_server_filename=gogs-server-url.txt


# utils ----------

function configure {
	# server url
	if [ -n "$(printenv $gogs_server_envvar)" ]; then
		gogs_server=$(printenv $gogs_server_envvar)
	elif [ -f "$gogs_server_filename" ]; then
		gogs_server=$(cat "$gogs_server_filename")
	elif [ $# -eq 0 ]; then
		echo No Gogs server URL \(e.g. https://try.gogs.io\) configured.
		read -p "URL: " gogs_server
		echo
		if [ -z "$gogs_server" ]; then exit 0; fi
	fi

	# api token
	if [ -n "$(printenv $gogs_token_envvar)" ]; then
		gogs_token=$(printenv $gogs_token_envvar)
	elif [ -f "$gogs_token_filename" ]; then
		gogs_token=$(cat "$gogs_token_filename")
	elif [ -f "$gogs_token_filename.gpg" ]; then
		gogs_token=$(gpg -q -d "$gogs_token_filename.gpg")
	elif [ $# -eq 0 ]; then
		echo No Gogs API token configured.
		read -sp "Token: " gogs_token
		echo
		echo
		if [ -z "$gogs_token" ]; then exit 0; fi
	fi
}

function run_curl_and_log {
	if [ $dev -eq 1 ]; then
		echo "$@" > log_curl_cmd.txt
		output=$("$@" 2> log_error.txt)
		echo "$output" > log_curl_response.txt
		echo -n "$output"
	else
		"$@" 2> /dev/null
	fi
}

function gogs-curl {
	method=$1
	cmd=$2
	data="$3"
	auth="?token=$gogs_token"
	address=$gogs_server"/api/v1"$cmd$auth

	if [ $debug -eq 1 ]; then
		echo $method
		echo -e "\tcommand: $cmd"
		echo -e "\taddress: $address"
		echo -e "\tdata:    $data"
	else
		echo
		sleep 1s
		if [ -n "$data" ]; then
			run_curl_and_log curl -d "$data" -H "Content-Type: application/json" -X $method "$address" --insecure
		else
			run_curl_and_log curl -X $method "$address" --insecure
		fi
	fi
}

function syntax-help {
	if [ $1 -gt $(( $# - 2 )) ]; then
		echo Required argument\(s\): $2
			exit 0
			fi
}

function split-json {
	if [ $# -gt 2 ]; then
		echo "$3"
	else
		cat
	fi | sed "s/$1$2/$1\n$2/g"
}

function json-property {
	if [ $# -gt 1 ]; then
		echo "$2"
	else
		cat
	fi | sed "0,/\"$1\"/{s/\"$1\"/@@@/}" | sed -nE "s/^.*@@@:(\
(true)|\
(false)|\
([0-9]+)|\
\"([^\"]*)\"|\
(\[[^]]*\])|\
(\
\{[^{}]*(\
\{[^{}]*(\
\{[^{}]*\}[^{}]*\
)*\}[^{}]*\
)*\}\
)\
).*$/\2\3\4\5\6\7/p"
}


# actions ----------

actions=$actions" create-org-repo"
function create-org-repo {
	syntax-help 4 "org-name repo-name description private:true/false" "$@"
	gogs-curl POST /org/$1/repos "{\"name\":\"$2\",\"description\":\"$3\",\"private\":$4}"
}

actions=$actions" create-user-repo"
function create-user-repo {
	syntax-help 4 "user-name repo-name description private:true/false" "$@"
	gogs-curl POST /admin/users/$1/repos "{\"name\":\"$2\",\"description\":\"$3\",\"private\":$4}"
}

actions=$actions" delete-repo"
function delete-repo {
	syntax-help 2 "user/org-name repo-name" "$@"
	gogs-curl DELETE /repos/$1/$2
}

actions=$actions" list-org-repos"
function list-org-repos {
	syntax-help 1 "org-name" "$@"
	gogs-curl GET /orgs/$1/repos | split-json "}}," "{" | json-property name
}

actions=$actions" list-user-repos"
function list-user-repos {
	syntax-help 1 "user-name" "$@"
	gogs-curl GET /users/$1/repos | split-json "}}," "{" | json-property name
}

actions=$actions" -"

actions=$actions" get-repo"
function get-repo {
	syntax-help 2 "user/org-name repo-name [property]" "$@"
	json="$(gogs-curl GET /repos/$1/$2)"
	if [ $debug -eq 1 ]; then
		echo "$json"
	else
		if [ -z $3 ]; then
			echo "$json"
		else
			echo "$json" | json-property "$3"
		fi
	fi
}

actions=$actions" enable-issues"
function enable-issues {
	syntax-help 3 "user/org-name repo-name enable:true/false" "$@"
	gogs-curl PATCH /repos/$1/$2/issue-tracker "{\"enable_issues\":$3}"
}

actions=$actions" -"

actions=$actions" create-team"
function create-team {
	syntax-help 3 "org-name team-name description [permission: read/write/admin]" "$@"
	gogs-curl POST /admin/orgs/$1/teams "{\"name\":\"$2\",\"description\":\"$3\",\"permission\":\"$4\"}"
}

actions=$actions" list-teams"
function list-teams {
	syntax-help 1 "org-name" "$@"
	gogs-curl GET /orgs/$1/teams | split-json "}," "{" | json-property name
}

actions=$actions" get-team-id"
function get-team-id {
	syntax-help 2 "org-name team-name" "$@"
	teams="$(gogs-curl GET /orgs/$1/teams)"
	if [ $debug -eq 1 ]; then
		echo "$teams"
	else
		echo -n $(echo "$teams" | split-json "}," "{" | grep "\"name\":\"$2\"" | json-property id)
	fi
}

actions=$actions" -"

actions=$actions" add-collaborator"
function add-collaborator {
	syntax-help 3 "user/org-name repo-name user-name [permission: read/write/admin]" "$@"
	gogs-curl PUT /repos/$1/$2/collaborators/$3 "{\"permission\":\"$4\"}"
}

actions=$actions" remove-collaborator"
function remove-collaborator {
	syntax-help 3 "user/org-name repo-name user-name" "$@"
	gogs-curl DELETE /repos/$1/$2/collaborators/$3
}

actions=$actions" list-collaborators"
function list-collaborators {
	syntax-help 2 "user/org-name repo-name" "$@"
	gogs-curl GET /repos/$1/$2/collaborators | split-json "}," "{" | json-property username
}

actions=$actions" -"

actions=$actions" add-team-member"
function add-team-member {
	syntax-help 2 "team-id user-name" "$@"
	gogs-curl PUT /admin/teams/$1/members/$2
}

actions=$actions" remove-team-member"
function remove-team-member {
	syntax-help 2 "team-id user-name" "$@"
	gogs-curl DELETE /admin/teams/$1/members/$2
}

actions=$actions" list-team-members"
function list-team-members {
	syntax-help 1 "team-id" "$@"
	gogs-curl GET /admin/teams/$1/members | split-json "}," "{" | json-property username
}

actions=$actions" -"

actions=$actions" add-team-repo"
function add-team-repo {
	syntax-help 2 "team-id repo-name" "$@"
	gogs-curl PUT /admin/teams/$1/repos/$2
}

actions=$actions" remove-team-repo"
function remove-team-repo {
	syntax-help 2 "team-id repo-name" "$@"
	gogs-curl DELETE /admin/teams/$1/repos/$2
}

actions=$actions" -"

actions=$actions" get-commit"
function get-commit {
	syntax-help 3 "user/org-name repo-name branch/tag/sha [property]" "$@"
	json="$(gogs-curl GET /repos/$1/$2/commits/$3)"
	if [ $debug -eq 1 ]; then
		echo "$json"
	else
		if [ -z $4 ]; then
			echo "$json"
		else
			echo "$json" | json-property "$4"
		fi
	fi
}

actions=$actions" get-raw"
function get-raw {
	syntax-help 3 "user/org-name repo-name ref" "$@"
	gogs-curl GET /repos/$1/$2/raw/$3
}


# cmd interface ----------

function print-help {
	echo
	echo \*\* Gogs command line interface \*\*
	echo
	echo "  "----------
	echo
	for action in $actions; do
		if [ "$action" == "-" ]; then
			echo
		else
			echo "  "$action
		fi
	done
	configure do-not-ask-if-not-configured
	echo
	echo "  "----------
	echo
	echo "  "Current configuration:
	echo
	echo -e "  "Server: $(if [ -z "$gogs_server" ]; then echo "\033[0;31m"NOT-CONFIGURED"\033[0m"; fi)$gogs_server
	echo "  "\(Change via environment variable $gogs_server_envvar or $gogs_server_filename\)
	echo
	echo -e "  "API token: $(if [ -z "$gogs_token" ]; then echo "\033[0;31m"NOT-CONFIGURED"\033[0m"; else echo ${gogs_token:0:5}...; fi)
	echo "  "\(Change via environment variable $gogs_token_envvar or $gogs_token_filename[.gpg]\)
	echo "  "\(Create one here: $(if [ -z "$gogs_server" ]; then echo https://YOUR.GOGS.SERVER; fi)$gogs_server/user/settings/applications\)
	echo
}

debug=0
dev=0
while [ -n "$1" ] && [[ "$1" == "-"* ]] && [ "$1" != "--" ]; do
	case "$1" in
		-d) debug=1; echo \# DRY RUN \(doing nothing\) ;;
		-D) dev=1; echo \# DEV RUN ;;
	esac
	shift
done

function run_action {
	action=$1
	if [ $dev -eq 1 ]; then
		echo \# action: $action
	fi
	configure
	if [ $dev -eq 1 ]; then
		echo \# configured \| URL: $gogs_server \| Token: $gogs_token
	fi
	"$@"
}

if [ $# -gt 0 ]; then
	action=$1
	shift
	for a in $actions; do
		if [ "$a" == "$action" ] && [ "$a" != "-" ]; then
			run_action $action "$@"
			exit 0
		fi
	done
	case $action in
		--help) print-help ;;
		--)
			action=$1
			shift
			run_action $action "$@"
			;;
		*) echo Unrecognized action: \"$action\" ;;
	esac
else
	print-help
fi
